main: ${groupId}.${artifactId}Plugin
name: ${artifactId}
version: ${version}

author: Ecconia
description: A plugin for autoplacing torches in a ROM.

commands:
    torcher:
        description: Place torches in a ROM automatically.
