main: ${groupId}.${artifactId}Plugin
name: ${artifactId}
version: ${version}

api-version: 1.20
depends: [WorldEdit]

author: Ecconia
description: A plugin for autoplacing torches in a ROM.

commands:
    torcher:
        description: Place torches in a ROM automatically.
        permission: torcher
